# Generated by Django 4.1.7 on 2023-05-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('discipline', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Cyber Security', 'Cyber Security'), ('Biochemistry', 'Biochemistry'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Business Administration', 'Business Administration'), ('Mass Communication', 'Mass Communication'), ('Criminology', 'Criminology'), ('Microbiology', 'Microbiology'), ('Economics', 'Economics'), ('Accounting', 'Accounting')], max_length=250)),
                ('institution', models.CharField(max_length=500)),
                ('graduation_date', models.DateField()),
                ('certificate_type', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Post Graduate', 'Post Graduate')], max_length=250)),
                ('certificate_no', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes')),
            ],
        ),
    ]
